// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module llama_layer_FFN_1 (
        m_axi_gmem2_0_AWVALID,
        m_axi_gmem2_0_AWREADY,
        m_axi_gmem2_0_AWADDR,
        m_axi_gmem2_0_AWID,
        m_axi_gmem2_0_AWLEN,
        m_axi_gmem2_0_AWSIZE,
        m_axi_gmem2_0_AWBURST,
        m_axi_gmem2_0_AWLOCK,
        m_axi_gmem2_0_AWCACHE,
        m_axi_gmem2_0_AWPROT,
        m_axi_gmem2_0_AWQOS,
        m_axi_gmem2_0_AWREGION,
        m_axi_gmem2_0_AWUSER,
        m_axi_gmem2_0_WVALID,
        m_axi_gmem2_0_WREADY,
        m_axi_gmem2_0_WDATA,
        m_axi_gmem2_0_WSTRB,
        m_axi_gmem2_0_WLAST,
        m_axi_gmem2_0_WID,
        m_axi_gmem2_0_WUSER,
        m_axi_gmem2_0_ARVALID,
        m_axi_gmem2_0_ARREADY,
        m_axi_gmem2_0_ARADDR,
        m_axi_gmem2_0_ARID,
        m_axi_gmem2_0_ARLEN,
        m_axi_gmem2_0_ARSIZE,
        m_axi_gmem2_0_ARBURST,
        m_axi_gmem2_0_ARLOCK,
        m_axi_gmem2_0_ARCACHE,
        m_axi_gmem2_0_ARPROT,
        m_axi_gmem2_0_ARQOS,
        m_axi_gmem2_0_ARREGION,
        m_axi_gmem2_0_ARUSER,
        m_axi_gmem2_0_RVALID,
        m_axi_gmem2_0_RREADY,
        m_axi_gmem2_0_RDATA,
        m_axi_gmem2_0_RLAST,
        m_axi_gmem2_0_RID,
        m_axi_gmem2_0_RFIFONUM,
        m_axi_gmem2_0_RUSER,
        m_axi_gmem2_0_RRESP,
        m_axi_gmem2_0_BVALID,
        m_axi_gmem2_0_BREADY,
        m_axi_gmem2_0_BRESP,
        m_axi_gmem2_0_BID,
        m_axi_gmem2_0_BUSER,
        W1_vec,
        W2_vec,
        W3_vec,
        ffn_input_address0,
        ffn_input_ce0,
        ffn_input_d0,
        ffn_input_q0,
        ffn_input_we0,
        ffn_input_address1,
        ffn_input_ce1,
        ffn_input_d1,
        ffn_input_q1,
        ffn_input_we1,
        ffn_input_44_address0,
        ffn_input_44_ce0,
        ffn_input_44_d0,
        ffn_input_44_q0,
        ffn_input_44_we0,
        ffn_input_44_address1,
        ffn_input_44_ce1,
        ffn_input_44_d1,
        ffn_input_44_q1,
        ffn_input_44_we1,
        ffn_input_45_address0,
        ffn_input_45_ce0,
        ffn_input_45_d0,
        ffn_input_45_q0,
        ffn_input_45_we0,
        ffn_input_45_address1,
        ffn_input_45_ce1,
        ffn_input_45_d1,
        ffn_input_45_q1,
        ffn_input_45_we1,
        ffn_input_46_address0,
        ffn_input_46_ce0,
        ffn_input_46_d0,
        ffn_input_46_q0,
        ffn_input_46_we0,
        ffn_input_46_address1,
        ffn_input_46_ce1,
        ffn_input_46_d1,
        ffn_input_46_q1,
        ffn_input_46_we1,
        ffn_input_47_address0,
        ffn_input_47_ce0,
        ffn_input_47_d0,
        ffn_input_47_q0,
        ffn_input_47_we0,
        ffn_input_47_address1,
        ffn_input_47_ce1,
        ffn_input_47_d1,
        ffn_input_47_q1,
        ffn_input_47_we1,
        ffn_input_48_address0,
        ffn_input_48_ce0,
        ffn_input_48_d0,
        ffn_input_48_q0,
        ffn_input_48_we0,
        ffn_input_48_address1,
        ffn_input_48_ce1,
        ffn_input_48_d1,
        ffn_input_48_q1,
        ffn_input_48_we1,
        ffn_input_49_address0,
        ffn_input_49_ce0,
        ffn_input_49_d0,
        ffn_input_49_q0,
        ffn_input_49_we0,
        ffn_input_49_address1,
        ffn_input_49_ce1,
        ffn_input_49_d1,
        ffn_input_49_q1,
        ffn_input_49_we1,
        ffn_input_50_address0,
        ffn_input_50_ce0,
        ffn_input_50_d0,
        ffn_input_50_q0,
        ffn_input_50_we0,
        ffn_input_50_address1,
        ffn_input_50_ce1,
        ffn_input_50_d1,
        ffn_input_50_q1,
        ffn_input_50_we1,
        p_ZZ11llama_layerE11norm_output_10_address0,
        p_ZZ11llama_layerE11norm_output_10_ce0,
        p_ZZ11llama_layerE11norm_output_10_d0,
        p_ZZ11llama_layerE11norm_output_10_q0,
        p_ZZ11llama_layerE11norm_output_10_we0,
        p_ZZ11llama_layerE11norm_output_10_address1,
        p_ZZ11llama_layerE11norm_output_10_ce1,
        p_ZZ11llama_layerE11norm_output_10_d1,
        p_ZZ11llama_layerE11norm_output_10_q1,
        p_ZZ11llama_layerE11norm_output_10_we1,
        p_ZZ11llama_layerE11norm_output_11_address0,
        p_ZZ11llama_layerE11norm_output_11_ce0,
        p_ZZ11llama_layerE11norm_output_11_d0,
        p_ZZ11llama_layerE11norm_output_11_q0,
        p_ZZ11llama_layerE11norm_output_11_we0,
        p_ZZ11llama_layerE11norm_output_11_address1,
        p_ZZ11llama_layerE11norm_output_11_ce1,
        p_ZZ11llama_layerE11norm_output_11_d1,
        p_ZZ11llama_layerE11norm_output_11_q1,
        p_ZZ11llama_layerE11norm_output_11_we1,
        p_ZZ11llama_layerE11norm_output_12_address0,
        p_ZZ11llama_layerE11norm_output_12_ce0,
        p_ZZ11llama_layerE11norm_output_12_d0,
        p_ZZ11llama_layerE11norm_output_12_q0,
        p_ZZ11llama_layerE11norm_output_12_we0,
        p_ZZ11llama_layerE11norm_output_12_address1,
        p_ZZ11llama_layerE11norm_output_12_ce1,
        p_ZZ11llama_layerE11norm_output_12_d1,
        p_ZZ11llama_layerE11norm_output_12_q1,
        p_ZZ11llama_layerE11norm_output_12_we1,
        p_ZZ11llama_layerE11norm_output_13_address0,
        p_ZZ11llama_layerE11norm_output_13_ce0,
        p_ZZ11llama_layerE11norm_output_13_d0,
        p_ZZ11llama_layerE11norm_output_13_q0,
        p_ZZ11llama_layerE11norm_output_13_we0,
        p_ZZ11llama_layerE11norm_output_13_address1,
        p_ZZ11llama_layerE11norm_output_13_ce1,
        p_ZZ11llama_layerE11norm_output_13_d1,
        p_ZZ11llama_layerE11norm_output_13_q1,
        p_ZZ11llama_layerE11norm_output_13_we1,
        p_ZZ11llama_layerE11norm_output_14_address0,
        p_ZZ11llama_layerE11norm_output_14_ce0,
        p_ZZ11llama_layerE11norm_output_14_d0,
        p_ZZ11llama_layerE11norm_output_14_q0,
        p_ZZ11llama_layerE11norm_output_14_we0,
        p_ZZ11llama_layerE11norm_output_14_address1,
        p_ZZ11llama_layerE11norm_output_14_ce1,
        p_ZZ11llama_layerE11norm_output_14_d1,
        p_ZZ11llama_layerE11norm_output_14_q1,
        p_ZZ11llama_layerE11norm_output_14_we1,
        p_ZZ11llama_layerE11norm_output_15_address0,
        p_ZZ11llama_layerE11norm_output_15_ce0,
        p_ZZ11llama_layerE11norm_output_15_d0,
        p_ZZ11llama_layerE11norm_output_15_q0,
        p_ZZ11llama_layerE11norm_output_15_we0,
        p_ZZ11llama_layerE11norm_output_15_address1,
        p_ZZ11llama_layerE11norm_output_15_ce1,
        p_ZZ11llama_layerE11norm_output_15_d1,
        p_ZZ11llama_layerE11norm_output_15_q1,
        p_ZZ11llama_layerE11norm_output_15_we1,
        norm_output_address0,
        norm_output_ce0,
        norm_output_d0,
        norm_output_q0,
        norm_output_we0,
        norm_output_address1,
        norm_output_ce1,
        norm_output_d1,
        norm_output_q1,
        norm_output_we1,
        norm_output_35_address0,
        norm_output_35_ce0,
        norm_output_35_d0,
        norm_output_35_q0,
        norm_output_35_we0,
        norm_output_35_address1,
        norm_output_35_ce1,
        norm_output_35_d1,
        norm_output_35_q1,
        norm_output_35_we1,
        norm_output_36_address0,
        norm_output_36_ce0,
        norm_output_36_d0,
        norm_output_36_q0,
        norm_output_36_we0,
        norm_output_36_address1,
        norm_output_36_ce1,
        norm_output_36_d1,
        norm_output_36_q1,
        norm_output_36_we1,
        norm_output_37_address0,
        norm_output_37_ce0,
        norm_output_37_d0,
        norm_output_37_q0,
        norm_output_37_we0,
        norm_output_37_address1,
        norm_output_37_ce1,
        norm_output_37_d1,
        norm_output_37_q1,
        norm_output_37_we1,
        norm_output_38_address0,
        norm_output_38_ce0,
        norm_output_38_d0,
        norm_output_38_q0,
        norm_output_38_we0,
        norm_output_38_address1,
        norm_output_38_ce1,
        norm_output_38_d1,
        norm_output_38_q1,
        norm_output_38_we1,
        norm_output_39_address0,
        norm_output_39_ce0,
        norm_output_39_d0,
        norm_output_39_q0,
        norm_output_39_we0,
        norm_output_39_address1,
        norm_output_39_ce1,
        norm_output_39_d1,
        norm_output_39_q1,
        norm_output_39_we1,
        norm_output_40_address0,
        norm_output_40_ce0,
        norm_output_40_d0,
        norm_output_40_q0,
        norm_output_40_we0,
        norm_output_40_address1,
        norm_output_40_ce1,
        norm_output_40_d1,
        norm_output_40_q1,
        norm_output_40_we1,
        norm_output_41_address0,
        norm_output_41_ce0,
        norm_output_41_d0,
        norm_output_41_q0,
        norm_output_41_we0,
        norm_output_41_address1,
        norm_output_41_ce1,
        norm_output_41_d1,
        norm_output_41_q1,
        norm_output_41_we1,
        norm_output_42_address0,
        norm_output_42_ce0,
        norm_output_42_d0,
        norm_output_42_q0,
        norm_output_42_we0,
        norm_output_42_address1,
        norm_output_42_ce1,
        norm_output_42_d1,
        norm_output_42_q1,
        norm_output_42_we1,
        norm_output_43_address0,
        norm_output_43_ce0,
        norm_output_43_d0,
        norm_output_43_q0,
        norm_output_43_we0,
        norm_output_43_address1,
        norm_output_43_ce1,
        norm_output_43_d1,
        norm_output_43_q1,
        norm_output_43_we1,
        ap_clk,
        ap_rst,
        W1_vec_ap_vld,
        W2_vec_ap_vld,
        W3_vec_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


output   m_axi_gmem2_0_AWVALID;
input   m_axi_gmem2_0_AWREADY;
output  [63:0] m_axi_gmem2_0_AWADDR;
output  [0:0] m_axi_gmem2_0_AWID;
output  [31:0] m_axi_gmem2_0_AWLEN;
output  [2:0] m_axi_gmem2_0_AWSIZE;
output  [1:0] m_axi_gmem2_0_AWBURST;
output  [1:0] m_axi_gmem2_0_AWLOCK;
output  [3:0] m_axi_gmem2_0_AWCACHE;
output  [2:0] m_axi_gmem2_0_AWPROT;
output  [3:0] m_axi_gmem2_0_AWQOS;
output  [3:0] m_axi_gmem2_0_AWREGION;
output  [0:0] m_axi_gmem2_0_AWUSER;
output   m_axi_gmem2_0_WVALID;
input   m_axi_gmem2_0_WREADY;
output  [31:0] m_axi_gmem2_0_WDATA;
output  [3:0] m_axi_gmem2_0_WSTRB;
output   m_axi_gmem2_0_WLAST;
output  [0:0] m_axi_gmem2_0_WID;
output  [0:0] m_axi_gmem2_0_WUSER;
output   m_axi_gmem2_0_ARVALID;
input   m_axi_gmem2_0_ARREADY;
output  [63:0] m_axi_gmem2_0_ARADDR;
output  [0:0] m_axi_gmem2_0_ARID;
output  [31:0] m_axi_gmem2_0_ARLEN;
output  [2:0] m_axi_gmem2_0_ARSIZE;
output  [1:0] m_axi_gmem2_0_ARBURST;
output  [1:0] m_axi_gmem2_0_ARLOCK;
output  [3:0] m_axi_gmem2_0_ARCACHE;
output  [2:0] m_axi_gmem2_0_ARPROT;
output  [3:0] m_axi_gmem2_0_ARQOS;
output  [3:0] m_axi_gmem2_0_ARREGION;
output  [0:0] m_axi_gmem2_0_ARUSER;
input   m_axi_gmem2_0_RVALID;
output   m_axi_gmem2_0_RREADY;
input  [31:0] m_axi_gmem2_0_RDATA;
input   m_axi_gmem2_0_RLAST;
input  [0:0] m_axi_gmem2_0_RID;
input  [12:0] m_axi_gmem2_0_RFIFONUM;
input  [0:0] m_axi_gmem2_0_RUSER;
input  [1:0] m_axi_gmem2_0_RRESP;
input   m_axi_gmem2_0_BVALID;
output   m_axi_gmem2_0_BREADY;
input  [1:0] m_axi_gmem2_0_BRESP;
input  [0:0] m_axi_gmem2_0_BID;
input  [0:0] m_axi_gmem2_0_BUSER;
input  [63:0] W1_vec;
input  [63:0] W2_vec;
input  [63:0] W3_vec;
output  [6:0] ffn_input_address0;
output   ffn_input_ce0;
output  [31:0] ffn_input_d0;
input  [31:0] ffn_input_q0;
output   ffn_input_we0;
output  [6:0] ffn_input_address1;
output   ffn_input_ce1;
output  [31:0] ffn_input_d1;
input  [31:0] ffn_input_q1;
output   ffn_input_we1;
output  [6:0] ffn_input_44_address0;
output   ffn_input_44_ce0;
output  [31:0] ffn_input_44_d0;
input  [31:0] ffn_input_44_q0;
output   ffn_input_44_we0;
output  [6:0] ffn_input_44_address1;
output   ffn_input_44_ce1;
output  [31:0] ffn_input_44_d1;
input  [31:0] ffn_input_44_q1;
output   ffn_input_44_we1;
output  [6:0] ffn_input_45_address0;
output   ffn_input_45_ce0;
output  [31:0] ffn_input_45_d0;
input  [31:0] ffn_input_45_q0;
output   ffn_input_45_we0;
output  [6:0] ffn_input_45_address1;
output   ffn_input_45_ce1;
output  [31:0] ffn_input_45_d1;
input  [31:0] ffn_input_45_q1;
output   ffn_input_45_we1;
output  [6:0] ffn_input_46_address0;
output   ffn_input_46_ce0;
output  [31:0] ffn_input_46_d0;
input  [31:0] ffn_input_46_q0;
output   ffn_input_46_we0;
output  [6:0] ffn_input_46_address1;
output   ffn_input_46_ce1;
output  [31:0] ffn_input_46_d1;
input  [31:0] ffn_input_46_q1;
output   ffn_input_46_we1;
output  [6:0] ffn_input_47_address0;
output   ffn_input_47_ce0;
output  [31:0] ffn_input_47_d0;
input  [31:0] ffn_input_47_q0;
output   ffn_input_47_we0;
output  [6:0] ffn_input_47_address1;
output   ffn_input_47_ce1;
output  [31:0] ffn_input_47_d1;
input  [31:0] ffn_input_47_q1;
output   ffn_input_47_we1;
output  [6:0] ffn_input_48_address0;
output   ffn_input_48_ce0;
output  [31:0] ffn_input_48_d0;
input  [31:0] ffn_input_48_q0;
output   ffn_input_48_we0;
output  [6:0] ffn_input_48_address1;
output   ffn_input_48_ce1;
output  [31:0] ffn_input_48_d1;
input  [31:0] ffn_input_48_q1;
output   ffn_input_48_we1;
output  [6:0] ffn_input_49_address0;
output   ffn_input_49_ce0;
output  [31:0] ffn_input_49_d0;
input  [31:0] ffn_input_49_q0;
output   ffn_input_49_we0;
output  [6:0] ffn_input_49_address1;
output   ffn_input_49_ce1;
output  [31:0] ffn_input_49_d1;
input  [31:0] ffn_input_49_q1;
output   ffn_input_49_we1;
output  [6:0] ffn_input_50_address0;
output   ffn_input_50_ce0;
output  [31:0] ffn_input_50_d0;
input  [31:0] ffn_input_50_q0;
output   ffn_input_50_we0;
output  [6:0] ffn_input_50_address1;
output   ffn_input_50_ce1;
output  [31:0] ffn_input_50_d1;
input  [31:0] ffn_input_50_q1;
output   ffn_input_50_we1;
output  [5:0] p_ZZ11llama_layerE11norm_output_10_address0;
output   p_ZZ11llama_layerE11norm_output_10_ce0;
output  [31:0] p_ZZ11llama_layerE11norm_output_10_d0;
input  [31:0] p_ZZ11llama_layerE11norm_output_10_q0;
output   p_ZZ11llama_layerE11norm_output_10_we0;
output  [5:0] p_ZZ11llama_layerE11norm_output_10_address1;
output   p_ZZ11llama_layerE11norm_output_10_ce1;
output  [31:0] p_ZZ11llama_layerE11norm_output_10_d1;
input  [31:0] p_ZZ11llama_layerE11norm_output_10_q1;
output   p_ZZ11llama_layerE11norm_output_10_we1;
output  [5:0] p_ZZ11llama_layerE11norm_output_11_address0;
output   p_ZZ11llama_layerE11norm_output_11_ce0;
output  [31:0] p_ZZ11llama_layerE11norm_output_11_d0;
input  [31:0] p_ZZ11llama_layerE11norm_output_11_q0;
output   p_ZZ11llama_layerE11norm_output_11_we0;
output  [5:0] p_ZZ11llama_layerE11norm_output_11_address1;
output   p_ZZ11llama_layerE11norm_output_11_ce1;
output  [31:0] p_ZZ11llama_layerE11norm_output_11_d1;
input  [31:0] p_ZZ11llama_layerE11norm_output_11_q1;
output   p_ZZ11llama_layerE11norm_output_11_we1;
output  [5:0] p_ZZ11llama_layerE11norm_output_12_address0;
output   p_ZZ11llama_layerE11norm_output_12_ce0;
output  [31:0] p_ZZ11llama_layerE11norm_output_12_d0;
input  [31:0] p_ZZ11llama_layerE11norm_output_12_q0;
output   p_ZZ11llama_layerE11norm_output_12_we0;
output  [5:0] p_ZZ11llama_layerE11norm_output_12_address1;
output   p_ZZ11llama_layerE11norm_output_12_ce1;
output  [31:0] p_ZZ11llama_layerE11norm_output_12_d1;
input  [31:0] p_ZZ11llama_layerE11norm_output_12_q1;
output   p_ZZ11llama_layerE11norm_output_12_we1;
output  [5:0] p_ZZ11llama_layerE11norm_output_13_address0;
output   p_ZZ11llama_layerE11norm_output_13_ce0;
output  [31:0] p_ZZ11llama_layerE11norm_output_13_d0;
input  [31:0] p_ZZ11llama_layerE11norm_output_13_q0;
output   p_ZZ11llama_layerE11norm_output_13_we0;
output  [5:0] p_ZZ11llama_layerE11norm_output_13_address1;
output   p_ZZ11llama_layerE11norm_output_13_ce1;
output  [31:0] p_ZZ11llama_layerE11norm_output_13_d1;
input  [31:0] p_ZZ11llama_layerE11norm_output_13_q1;
output   p_ZZ11llama_layerE11norm_output_13_we1;
output  [5:0] p_ZZ11llama_layerE11norm_output_14_address0;
output   p_ZZ11llama_layerE11norm_output_14_ce0;
output  [31:0] p_ZZ11llama_layerE11norm_output_14_d0;
input  [31:0] p_ZZ11llama_layerE11norm_output_14_q0;
output   p_ZZ11llama_layerE11norm_output_14_we0;
output  [5:0] p_ZZ11llama_layerE11norm_output_14_address1;
output   p_ZZ11llama_layerE11norm_output_14_ce1;
output  [31:0] p_ZZ11llama_layerE11norm_output_14_d1;
input  [31:0] p_ZZ11llama_layerE11norm_output_14_q1;
output   p_ZZ11llama_layerE11norm_output_14_we1;
output  [5:0] p_ZZ11llama_layerE11norm_output_15_address0;
output   p_ZZ11llama_layerE11norm_output_15_ce0;
output  [31:0] p_ZZ11llama_layerE11norm_output_15_d0;
input  [31:0] p_ZZ11llama_layerE11norm_output_15_q0;
output   p_ZZ11llama_layerE11norm_output_15_we0;
output  [5:0] p_ZZ11llama_layerE11norm_output_15_address1;
output   p_ZZ11llama_layerE11norm_output_15_ce1;
output  [31:0] p_ZZ11llama_layerE11norm_output_15_d1;
input  [31:0] p_ZZ11llama_layerE11norm_output_15_q1;
output   p_ZZ11llama_layerE11norm_output_15_we1;
output  [5:0] norm_output_address0;
output   norm_output_ce0;
output  [31:0] norm_output_d0;
input  [31:0] norm_output_q0;
output   norm_output_we0;
output  [5:0] norm_output_address1;
output   norm_output_ce1;
output  [31:0] norm_output_d1;
input  [31:0] norm_output_q1;
output   norm_output_we1;
output  [5:0] norm_output_35_address0;
output   norm_output_35_ce0;
output  [31:0] norm_output_35_d0;
input  [31:0] norm_output_35_q0;
output   norm_output_35_we0;
output  [5:0] norm_output_35_address1;
output   norm_output_35_ce1;
output  [31:0] norm_output_35_d1;
input  [31:0] norm_output_35_q1;
output   norm_output_35_we1;
output  [5:0] norm_output_36_address0;
output   norm_output_36_ce0;
output  [31:0] norm_output_36_d0;
input  [31:0] norm_output_36_q0;
output   norm_output_36_we0;
output  [5:0] norm_output_36_address1;
output   norm_output_36_ce1;
output  [31:0] norm_output_36_d1;
input  [31:0] norm_output_36_q1;
output   norm_output_36_we1;
output  [5:0] norm_output_37_address0;
output   norm_output_37_ce0;
output  [31:0] norm_output_37_d0;
input  [31:0] norm_output_37_q0;
output   norm_output_37_we0;
output  [5:0] norm_output_37_address1;
output   norm_output_37_ce1;
output  [31:0] norm_output_37_d1;
input  [31:0] norm_output_37_q1;
output   norm_output_37_we1;
output  [5:0] norm_output_38_address0;
output   norm_output_38_ce0;
output  [31:0] norm_output_38_d0;
input  [31:0] norm_output_38_q0;
output   norm_output_38_we0;
output  [5:0] norm_output_38_address1;
output   norm_output_38_ce1;
output  [31:0] norm_output_38_d1;
input  [31:0] norm_output_38_q1;
output   norm_output_38_we1;
output  [5:0] norm_output_39_address0;
output   norm_output_39_ce0;
output  [31:0] norm_output_39_d0;
input  [31:0] norm_output_39_q0;
output   norm_output_39_we0;
output  [5:0] norm_output_39_address1;
output   norm_output_39_ce1;
output  [31:0] norm_output_39_d1;
input  [31:0] norm_output_39_q1;
output   norm_output_39_we1;
output  [5:0] norm_output_40_address0;
output   norm_output_40_ce0;
output  [31:0] norm_output_40_d0;
input  [31:0] norm_output_40_q0;
output   norm_output_40_we0;
output  [5:0] norm_output_40_address1;
output   norm_output_40_ce1;
output  [31:0] norm_output_40_d1;
input  [31:0] norm_output_40_q1;
output   norm_output_40_we1;
output  [5:0] norm_output_41_address0;
output   norm_output_41_ce0;
output  [31:0] norm_output_41_d0;
input  [31:0] norm_output_41_q0;
output   norm_output_41_we0;
output  [5:0] norm_output_41_address1;
output   norm_output_41_ce1;
output  [31:0] norm_output_41_d1;
input  [31:0] norm_output_41_q1;
output   norm_output_41_we1;
output  [5:0] norm_output_42_address0;
output   norm_output_42_ce0;
output  [31:0] norm_output_42_d0;
input  [31:0] norm_output_42_q0;
output   norm_output_42_we0;
output  [5:0] norm_output_42_address1;
output   norm_output_42_ce1;
output  [31:0] norm_output_42_d1;
input  [31:0] norm_output_42_q1;
output   norm_output_42_we1;
output  [5:0] norm_output_43_address0;
output   norm_output_43_ce0;
output  [31:0] norm_output_43_d0;
input  [31:0] norm_output_43_q0;
output   norm_output_43_we0;
output  [5:0] norm_output_43_address1;
output   norm_output_43_ce1;
output  [31:0] norm_output_43_d1;
input  [31:0] norm_output_43_q1;
output   norm_output_43_we1;
input   ap_clk;
input   ap_rst;
input   W1_vec_ap_vld;
input   W2_vec_ap_vld;
input   W3_vec_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ap_start;
wire    FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ap_done;
wire    FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ap_continue;
wire    FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ap_idle;
wire    FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ap_ready;
wire    FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_start_out;
wire    FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_start_write;
wire    FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWVALID;
wire   [63:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWADDR;
wire   [0:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWID;
wire   [31:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWLEN;
wire   [2:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWSIZE;
wire   [1:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWBURST;
wire   [1:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWLOCK;
wire   [3:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWCACHE;
wire   [2:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWPROT;
wire   [3:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWQOS;
wire   [3:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWREGION;
wire   [0:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWUSER;
wire    FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_WVALID;
wire   [31:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_WDATA;
wire   [3:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_WSTRB;
wire    FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_WLAST;
wire   [0:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_WID;
wire   [0:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_WUSER;
wire    FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARVALID;
wire   [63:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARADDR;
wire   [0:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARID;
wire   [31:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARLEN;
wire   [2:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARSIZE;
wire   [1:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARBURST;
wire   [1:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARLOCK;
wire   [3:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARCACHE;
wire   [2:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARPROT;
wire   [3:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARQOS;
wire   [3:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARREGION;
wire   [0:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARUSER;
wire    FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_RREADY;
wire    FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_BREADY;
wire   [31:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_res_strm_din;
wire    FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_res_strm_write;
wire   [6:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_address0;
wire    FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_ce0;
wire   [6:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_44_address0;
wire    FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_44_ce0;
wire   [6:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_45_address0;
wire    FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_45_ce0;
wire   [6:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_46_address0;
wire    FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_46_ce0;
wire   [6:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_47_address0;
wire    FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_47_ce0;
wire   [6:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_48_address0;
wire    FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_48_ce0;
wire   [6:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_49_address0;
wire    FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_49_ce0;
wire   [6:0] FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_50_address0;
wire    FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_50_ce0;
wire    pull_tensor1d_U0_ap_start;
wire    pull_tensor1d_U0_ap_done;
wire    pull_tensor1d_U0_ap_continue;
wire    pull_tensor1d_U0_ap_idle;
wire    pull_tensor1d_U0_ap_ready;
wire    pull_tensor1d_U0_res_strm_read;
wire   [5:0] pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_10_address1;
wire    pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_10_ce1;
wire    pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_10_we1;
wire   [31:0] pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_10_d1;
wire   [5:0] pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_11_address1;
wire    pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_11_ce1;
wire    pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_11_we1;
wire   [31:0] pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_11_d1;
wire   [5:0] pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_12_address1;
wire    pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_12_ce1;
wire    pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_12_we1;
wire   [31:0] pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_12_d1;
wire   [5:0] pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_13_address1;
wire    pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_13_ce1;
wire    pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_13_we1;
wire   [31:0] pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_13_d1;
wire   [5:0] pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_14_address1;
wire    pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_14_ce1;
wire    pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_14_we1;
wire   [31:0] pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_14_d1;
wire   [5:0] pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_15_address1;
wire    pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_15_ce1;
wire    pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_15_we1;
wire   [31:0] pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_15_d1;
wire   [5:0] pull_tensor1d_U0_norm_output_address1;
wire    pull_tensor1d_U0_norm_output_ce1;
wire    pull_tensor1d_U0_norm_output_we1;
wire   [31:0] pull_tensor1d_U0_norm_output_d1;
wire   [5:0] pull_tensor1d_U0_norm_output_35_address1;
wire    pull_tensor1d_U0_norm_output_35_ce1;
wire    pull_tensor1d_U0_norm_output_35_we1;
wire   [31:0] pull_tensor1d_U0_norm_output_35_d1;
wire   [5:0] pull_tensor1d_U0_norm_output_36_address1;
wire    pull_tensor1d_U0_norm_output_36_ce1;
wire    pull_tensor1d_U0_norm_output_36_we1;
wire   [31:0] pull_tensor1d_U0_norm_output_36_d1;
wire   [5:0] pull_tensor1d_U0_norm_output_37_address1;
wire    pull_tensor1d_U0_norm_output_37_ce1;
wire    pull_tensor1d_U0_norm_output_37_we1;
wire   [31:0] pull_tensor1d_U0_norm_output_37_d1;
wire   [5:0] pull_tensor1d_U0_norm_output_38_address1;
wire    pull_tensor1d_U0_norm_output_38_ce1;
wire    pull_tensor1d_U0_norm_output_38_we1;
wire   [31:0] pull_tensor1d_U0_norm_output_38_d1;
wire   [5:0] pull_tensor1d_U0_norm_output_39_address1;
wire    pull_tensor1d_U0_norm_output_39_ce1;
wire    pull_tensor1d_U0_norm_output_39_we1;
wire   [31:0] pull_tensor1d_U0_norm_output_39_d1;
wire   [5:0] pull_tensor1d_U0_norm_output_40_address1;
wire    pull_tensor1d_U0_norm_output_40_ce1;
wire    pull_tensor1d_U0_norm_output_40_we1;
wire   [31:0] pull_tensor1d_U0_norm_output_40_d1;
wire   [5:0] pull_tensor1d_U0_norm_output_41_address1;
wire    pull_tensor1d_U0_norm_output_41_ce1;
wire    pull_tensor1d_U0_norm_output_41_we1;
wire   [31:0] pull_tensor1d_U0_norm_output_41_d1;
wire   [5:0] pull_tensor1d_U0_norm_output_42_address1;
wire    pull_tensor1d_U0_norm_output_42_ce1;
wire    pull_tensor1d_U0_norm_output_42_we1;
wire   [31:0] pull_tensor1d_U0_norm_output_42_d1;
wire   [5:0] pull_tensor1d_U0_norm_output_43_address1;
wire    pull_tensor1d_U0_norm_output_43_ce1;
wire    pull_tensor1d_U0_norm_output_43_we1;
wire   [31:0] pull_tensor1d_U0_norm_output_43_d1;
wire    res_strm_full_n;
wire   [31:0] res_strm_dout;
wire    res_strm_empty_n;
wire   [6:0] res_strm_num_data_valid;
wire   [6:0] res_strm_fifo_cap;
wire   [0:0] start_for_pull_tensor1d_U0_din;
wire    start_for_pull_tensor1d_U0_full_n;
wire   [0:0] start_for_pull_tensor1d_U0_dout;
wire    start_for_pull_tensor1d_U0_empty_n;

llama_layer_FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ap_start),
    .start_full_n(start_for_pull_tensor1d_U0_full_n),
    .ap_done(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ap_done),
    .ap_continue(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ap_continue),
    .ap_idle(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ap_idle),
    .ap_ready(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ap_ready),
    .start_out(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_start_out),
    .start_write(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_start_write),
    .m_axi_gmem2_0_AWVALID(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWVALID),
    .m_axi_gmem2_0_AWREADY(1'b0),
    .m_axi_gmem2_0_AWADDR(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWADDR),
    .m_axi_gmem2_0_AWID(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWID),
    .m_axi_gmem2_0_AWLEN(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWLEN),
    .m_axi_gmem2_0_AWSIZE(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWSIZE),
    .m_axi_gmem2_0_AWBURST(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWBURST),
    .m_axi_gmem2_0_AWLOCK(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWLOCK),
    .m_axi_gmem2_0_AWCACHE(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWCACHE),
    .m_axi_gmem2_0_AWPROT(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWPROT),
    .m_axi_gmem2_0_AWQOS(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWQOS),
    .m_axi_gmem2_0_AWREGION(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWREGION),
    .m_axi_gmem2_0_AWUSER(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_AWUSER),
    .m_axi_gmem2_0_WVALID(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_WVALID),
    .m_axi_gmem2_0_WREADY(1'b0),
    .m_axi_gmem2_0_WDATA(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_WDATA),
    .m_axi_gmem2_0_WSTRB(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_WSTRB),
    .m_axi_gmem2_0_WLAST(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_WLAST),
    .m_axi_gmem2_0_WID(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_WID),
    .m_axi_gmem2_0_WUSER(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_WUSER),
    .m_axi_gmem2_0_ARVALID(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARVALID),
    .m_axi_gmem2_0_ARREADY(m_axi_gmem2_0_ARREADY),
    .m_axi_gmem2_0_ARADDR(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARADDR),
    .m_axi_gmem2_0_ARID(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARID),
    .m_axi_gmem2_0_ARLEN(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARLEN),
    .m_axi_gmem2_0_ARSIZE(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARSIZE),
    .m_axi_gmem2_0_ARBURST(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARBURST),
    .m_axi_gmem2_0_ARLOCK(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARLOCK),
    .m_axi_gmem2_0_ARCACHE(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARCACHE),
    .m_axi_gmem2_0_ARPROT(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARPROT),
    .m_axi_gmem2_0_ARQOS(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARQOS),
    .m_axi_gmem2_0_ARREGION(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARREGION),
    .m_axi_gmem2_0_ARUSER(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARUSER),
    .m_axi_gmem2_0_RVALID(m_axi_gmem2_0_RVALID),
    .m_axi_gmem2_0_RREADY(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_RREADY),
    .m_axi_gmem2_0_RDATA(m_axi_gmem2_0_RDATA),
    .m_axi_gmem2_0_RLAST(m_axi_gmem2_0_RLAST),
    .m_axi_gmem2_0_RID(m_axi_gmem2_0_RID),
    .m_axi_gmem2_0_RFIFONUM(m_axi_gmem2_0_RFIFONUM),
    .m_axi_gmem2_0_RUSER(m_axi_gmem2_0_RUSER),
    .m_axi_gmem2_0_RRESP(m_axi_gmem2_0_RRESP),
    .m_axi_gmem2_0_BVALID(1'b0),
    .m_axi_gmem2_0_BREADY(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_BREADY),
    .m_axi_gmem2_0_BRESP(2'd0),
    .m_axi_gmem2_0_BID(1'd0),
    .m_axi_gmem2_0_BUSER(1'd0),
    .W1_vec(W1_vec),
    .W2_vec(W2_vec),
    .W3_vec(W3_vec),
    .res_strm_din(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_res_strm_din),
    .res_strm_full_n(res_strm_full_n),
    .res_strm_write(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_res_strm_write),
    .res_strm_num_data_valid(res_strm_num_data_valid),
    .res_strm_fifo_cap(res_strm_fifo_cap),
    .ffn_input_address0(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_address0),
    .ffn_input_ce0(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_ce0),
    .ffn_input_q0(ffn_input_q0),
    .ffn_input_44_address0(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_44_address0),
    .ffn_input_44_ce0(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_44_ce0),
    .ffn_input_44_q0(ffn_input_44_q0),
    .ffn_input_45_address0(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_45_address0),
    .ffn_input_45_ce0(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_45_ce0),
    .ffn_input_45_q0(ffn_input_45_q0),
    .ffn_input_46_address0(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_46_address0),
    .ffn_input_46_ce0(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_46_ce0),
    .ffn_input_46_q0(ffn_input_46_q0),
    .ffn_input_47_address0(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_47_address0),
    .ffn_input_47_ce0(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_47_ce0),
    .ffn_input_47_q0(ffn_input_47_q0),
    .ffn_input_48_address0(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_48_address0),
    .ffn_input_48_ce0(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_48_ce0),
    .ffn_input_48_q0(ffn_input_48_q0),
    .ffn_input_49_address0(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_49_address0),
    .ffn_input_49_ce0(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_49_ce0),
    .ffn_input_49_q0(ffn_input_49_q0),
    .ffn_input_50_address0(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_50_address0),
    .ffn_input_50_ce0(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_50_ce0),
    .ffn_input_50_q0(ffn_input_50_q0)
);

llama_layer_pull_tensor1d pull_tensor1d_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(pull_tensor1d_U0_ap_start),
    .ap_done(pull_tensor1d_U0_ap_done),
    .ap_continue(pull_tensor1d_U0_ap_continue),
    .ap_idle(pull_tensor1d_U0_ap_idle),
    .ap_ready(pull_tensor1d_U0_ap_ready),
    .res_strm_dout(res_strm_dout),
    .res_strm_empty_n(res_strm_empty_n),
    .res_strm_read(pull_tensor1d_U0_res_strm_read),
    .res_strm_num_data_valid(res_strm_num_data_valid),
    .res_strm_fifo_cap(res_strm_fifo_cap),
    .p_ZZ11llama_layerE11norm_output_10_address1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_10_address1),
    .p_ZZ11llama_layerE11norm_output_10_ce1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_10_ce1),
    .p_ZZ11llama_layerE11norm_output_10_we1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_10_we1),
    .p_ZZ11llama_layerE11norm_output_10_d1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_10_d1),
    .p_ZZ11llama_layerE11norm_output_11_address1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_11_address1),
    .p_ZZ11llama_layerE11norm_output_11_ce1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_11_ce1),
    .p_ZZ11llama_layerE11norm_output_11_we1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_11_we1),
    .p_ZZ11llama_layerE11norm_output_11_d1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_11_d1),
    .p_ZZ11llama_layerE11norm_output_12_address1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_12_address1),
    .p_ZZ11llama_layerE11norm_output_12_ce1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_12_ce1),
    .p_ZZ11llama_layerE11norm_output_12_we1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_12_we1),
    .p_ZZ11llama_layerE11norm_output_12_d1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_12_d1),
    .p_ZZ11llama_layerE11norm_output_13_address1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_13_address1),
    .p_ZZ11llama_layerE11norm_output_13_ce1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_13_ce1),
    .p_ZZ11llama_layerE11norm_output_13_we1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_13_we1),
    .p_ZZ11llama_layerE11norm_output_13_d1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_13_d1),
    .p_ZZ11llama_layerE11norm_output_14_address1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_14_address1),
    .p_ZZ11llama_layerE11norm_output_14_ce1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_14_ce1),
    .p_ZZ11llama_layerE11norm_output_14_we1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_14_we1),
    .p_ZZ11llama_layerE11norm_output_14_d1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_14_d1),
    .p_ZZ11llama_layerE11norm_output_15_address1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_15_address1),
    .p_ZZ11llama_layerE11norm_output_15_ce1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_15_ce1),
    .p_ZZ11llama_layerE11norm_output_15_we1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_15_we1),
    .p_ZZ11llama_layerE11norm_output_15_d1(pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_15_d1),
    .norm_output_address1(pull_tensor1d_U0_norm_output_address1),
    .norm_output_ce1(pull_tensor1d_U0_norm_output_ce1),
    .norm_output_we1(pull_tensor1d_U0_norm_output_we1),
    .norm_output_d1(pull_tensor1d_U0_norm_output_d1),
    .norm_output_35_address1(pull_tensor1d_U0_norm_output_35_address1),
    .norm_output_35_ce1(pull_tensor1d_U0_norm_output_35_ce1),
    .norm_output_35_we1(pull_tensor1d_U0_norm_output_35_we1),
    .norm_output_35_d1(pull_tensor1d_U0_norm_output_35_d1),
    .norm_output_36_address1(pull_tensor1d_U0_norm_output_36_address1),
    .norm_output_36_ce1(pull_tensor1d_U0_norm_output_36_ce1),
    .norm_output_36_we1(pull_tensor1d_U0_norm_output_36_we1),
    .norm_output_36_d1(pull_tensor1d_U0_norm_output_36_d1),
    .norm_output_37_address1(pull_tensor1d_U0_norm_output_37_address1),
    .norm_output_37_ce1(pull_tensor1d_U0_norm_output_37_ce1),
    .norm_output_37_we1(pull_tensor1d_U0_norm_output_37_we1),
    .norm_output_37_d1(pull_tensor1d_U0_norm_output_37_d1),
    .norm_output_38_address1(pull_tensor1d_U0_norm_output_38_address1),
    .norm_output_38_ce1(pull_tensor1d_U0_norm_output_38_ce1),
    .norm_output_38_we1(pull_tensor1d_U0_norm_output_38_we1),
    .norm_output_38_d1(pull_tensor1d_U0_norm_output_38_d1),
    .norm_output_39_address1(pull_tensor1d_U0_norm_output_39_address1),
    .norm_output_39_ce1(pull_tensor1d_U0_norm_output_39_ce1),
    .norm_output_39_we1(pull_tensor1d_U0_norm_output_39_we1),
    .norm_output_39_d1(pull_tensor1d_U0_norm_output_39_d1),
    .norm_output_40_address1(pull_tensor1d_U0_norm_output_40_address1),
    .norm_output_40_ce1(pull_tensor1d_U0_norm_output_40_ce1),
    .norm_output_40_we1(pull_tensor1d_U0_norm_output_40_we1),
    .norm_output_40_d1(pull_tensor1d_U0_norm_output_40_d1),
    .norm_output_41_address1(pull_tensor1d_U0_norm_output_41_address1),
    .norm_output_41_ce1(pull_tensor1d_U0_norm_output_41_ce1),
    .norm_output_41_we1(pull_tensor1d_U0_norm_output_41_we1),
    .norm_output_41_d1(pull_tensor1d_U0_norm_output_41_d1),
    .norm_output_42_address1(pull_tensor1d_U0_norm_output_42_address1),
    .norm_output_42_ce1(pull_tensor1d_U0_norm_output_42_ce1),
    .norm_output_42_we1(pull_tensor1d_U0_norm_output_42_we1),
    .norm_output_42_d1(pull_tensor1d_U0_norm_output_42_d1),
    .norm_output_43_address1(pull_tensor1d_U0_norm_output_43_address1),
    .norm_output_43_ce1(pull_tensor1d_U0_norm_output_43_ce1),
    .norm_output_43_we1(pull_tensor1d_U0_norm_output_43_we1),
    .norm_output_43_d1(pull_tensor1d_U0_norm_output_43_d1)
);

llama_layer_fifo_w32_d64_A_x3 res_strm_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_res_strm_din),
    .if_full_n(res_strm_full_n),
    .if_write(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_res_strm_write),
    .if_dout(res_strm_dout),
    .if_empty_n(res_strm_empty_n),
    .if_read(pull_tensor1d_U0_res_strm_read),
    .if_num_data_valid(res_strm_num_data_valid),
    .if_fifo_cap(res_strm_fifo_cap)
);

llama_layer_start_for_pull_tensor1d_U0 start_for_pull_tensor1d_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pull_tensor1d_U0_din),
    .if_full_n(start_for_pull_tensor1d_U0_full_n),
    .if_write(FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_start_write),
    .if_dout(start_for_pull_tensor1d_U0_dout),
    .if_empty_n(start_for_pull_tensor1d_U0_empty_n),
    .if_read(pull_tensor1d_U0_ap_ready)
);

assign FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ap_continue = 1'b1;

assign FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ap_start = ap_start;

assign ap_done = pull_tensor1d_U0_ap_done;

assign ap_idle = (pull_tensor1d_U0_ap_idle & FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ap_idle);

assign ap_ready = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ap_ready;

assign ffn_input_44_address0 = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_44_address0;

assign ffn_input_44_address1 = 7'd0;

assign ffn_input_44_ce0 = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_44_ce0;

assign ffn_input_44_ce1 = 1'b0;

assign ffn_input_44_d0 = 32'd0;

assign ffn_input_44_d1 = 32'd0;

assign ffn_input_44_we0 = 1'b0;

assign ffn_input_44_we1 = 1'b0;

assign ffn_input_45_address0 = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_45_address0;

assign ffn_input_45_address1 = 7'd0;

assign ffn_input_45_ce0 = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_45_ce0;

assign ffn_input_45_ce1 = 1'b0;

assign ffn_input_45_d0 = 32'd0;

assign ffn_input_45_d1 = 32'd0;

assign ffn_input_45_we0 = 1'b0;

assign ffn_input_45_we1 = 1'b0;

assign ffn_input_46_address0 = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_46_address0;

assign ffn_input_46_address1 = 7'd0;

assign ffn_input_46_ce0 = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_46_ce0;

assign ffn_input_46_ce1 = 1'b0;

assign ffn_input_46_d0 = 32'd0;

assign ffn_input_46_d1 = 32'd0;

assign ffn_input_46_we0 = 1'b0;

assign ffn_input_46_we1 = 1'b0;

assign ffn_input_47_address0 = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_47_address0;

assign ffn_input_47_address1 = 7'd0;

assign ffn_input_47_ce0 = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_47_ce0;

assign ffn_input_47_ce1 = 1'b0;

assign ffn_input_47_d0 = 32'd0;

assign ffn_input_47_d1 = 32'd0;

assign ffn_input_47_we0 = 1'b0;

assign ffn_input_47_we1 = 1'b0;

assign ffn_input_48_address0 = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_48_address0;

assign ffn_input_48_address1 = 7'd0;

assign ffn_input_48_ce0 = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_48_ce0;

assign ffn_input_48_ce1 = 1'b0;

assign ffn_input_48_d0 = 32'd0;

assign ffn_input_48_d1 = 32'd0;

assign ffn_input_48_we0 = 1'b0;

assign ffn_input_48_we1 = 1'b0;

assign ffn_input_49_address0 = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_49_address0;

assign ffn_input_49_address1 = 7'd0;

assign ffn_input_49_ce0 = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_49_ce0;

assign ffn_input_49_ce1 = 1'b0;

assign ffn_input_49_d0 = 32'd0;

assign ffn_input_49_d1 = 32'd0;

assign ffn_input_49_we0 = 1'b0;

assign ffn_input_49_we1 = 1'b0;

assign ffn_input_50_address0 = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_50_address0;

assign ffn_input_50_address1 = 7'd0;

assign ffn_input_50_ce0 = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_50_ce0;

assign ffn_input_50_ce1 = 1'b0;

assign ffn_input_50_d0 = 32'd0;

assign ffn_input_50_d1 = 32'd0;

assign ffn_input_50_we0 = 1'b0;

assign ffn_input_50_we1 = 1'b0;

assign ffn_input_address0 = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_address0;

assign ffn_input_address1 = 7'd0;

assign ffn_input_ce0 = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_ffn_input_ce0;

assign ffn_input_ce1 = 1'b0;

assign ffn_input_d0 = 32'd0;

assign ffn_input_d1 = 32'd0;

assign ffn_input_we0 = 1'b0;

assign ffn_input_we1 = 1'b0;

assign m_axi_gmem2_0_ARADDR = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARADDR;

assign m_axi_gmem2_0_ARBURST = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARBURST;

assign m_axi_gmem2_0_ARCACHE = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARCACHE;

assign m_axi_gmem2_0_ARID = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARID;

assign m_axi_gmem2_0_ARLEN = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARLEN;

assign m_axi_gmem2_0_ARLOCK = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARLOCK;

assign m_axi_gmem2_0_ARPROT = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARPROT;

assign m_axi_gmem2_0_ARQOS = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARQOS;

assign m_axi_gmem2_0_ARREGION = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARREGION;

assign m_axi_gmem2_0_ARSIZE = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARSIZE;

assign m_axi_gmem2_0_ARUSER = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARUSER;

assign m_axi_gmem2_0_ARVALID = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_ARVALID;

assign m_axi_gmem2_0_AWADDR = 64'd0;

assign m_axi_gmem2_0_AWBURST = 2'd0;

assign m_axi_gmem2_0_AWCACHE = 4'd0;

assign m_axi_gmem2_0_AWID = 1'd0;

assign m_axi_gmem2_0_AWLEN = 32'd0;

assign m_axi_gmem2_0_AWLOCK = 2'd0;

assign m_axi_gmem2_0_AWPROT = 3'd0;

assign m_axi_gmem2_0_AWQOS = 4'd0;

assign m_axi_gmem2_0_AWREGION = 4'd0;

assign m_axi_gmem2_0_AWSIZE = 3'd0;

assign m_axi_gmem2_0_AWUSER = 1'd0;

assign m_axi_gmem2_0_AWVALID = 1'b0;

assign m_axi_gmem2_0_BREADY = 1'b0;

assign m_axi_gmem2_0_RREADY = FFN_1_Block_entry_x_strm_wr_x_strm_rd_W_strm_wr_W_strm_rd_proc_U0_m_axi_gmem2_0_RREADY;

assign m_axi_gmem2_0_WDATA = 32'd0;

assign m_axi_gmem2_0_WID = 1'd0;

assign m_axi_gmem2_0_WLAST = 1'b0;

assign m_axi_gmem2_0_WSTRB = 4'd0;

assign m_axi_gmem2_0_WUSER = 1'd0;

assign m_axi_gmem2_0_WVALID = 1'b0;

assign norm_output_35_address0 = 6'd0;

assign norm_output_35_address1 = pull_tensor1d_U0_norm_output_35_address1;

assign norm_output_35_ce0 = 1'b0;

assign norm_output_35_ce1 = pull_tensor1d_U0_norm_output_35_ce1;

assign norm_output_35_d0 = 32'd0;

assign norm_output_35_d1 = pull_tensor1d_U0_norm_output_35_d1;

assign norm_output_35_we0 = 1'b0;

assign norm_output_35_we1 = pull_tensor1d_U0_norm_output_35_we1;

assign norm_output_36_address0 = 6'd0;

assign norm_output_36_address1 = pull_tensor1d_U0_norm_output_36_address1;

assign norm_output_36_ce0 = 1'b0;

assign norm_output_36_ce1 = pull_tensor1d_U0_norm_output_36_ce1;

assign norm_output_36_d0 = 32'd0;

assign norm_output_36_d1 = pull_tensor1d_U0_norm_output_36_d1;

assign norm_output_36_we0 = 1'b0;

assign norm_output_36_we1 = pull_tensor1d_U0_norm_output_36_we1;

assign norm_output_37_address0 = 6'd0;

assign norm_output_37_address1 = pull_tensor1d_U0_norm_output_37_address1;

assign norm_output_37_ce0 = 1'b0;

assign norm_output_37_ce1 = pull_tensor1d_U0_norm_output_37_ce1;

assign norm_output_37_d0 = 32'd0;

assign norm_output_37_d1 = pull_tensor1d_U0_norm_output_37_d1;

assign norm_output_37_we0 = 1'b0;

assign norm_output_37_we1 = pull_tensor1d_U0_norm_output_37_we1;

assign norm_output_38_address0 = 6'd0;

assign norm_output_38_address1 = pull_tensor1d_U0_norm_output_38_address1;

assign norm_output_38_ce0 = 1'b0;

assign norm_output_38_ce1 = pull_tensor1d_U0_norm_output_38_ce1;

assign norm_output_38_d0 = 32'd0;

assign norm_output_38_d1 = pull_tensor1d_U0_norm_output_38_d1;

assign norm_output_38_we0 = 1'b0;

assign norm_output_38_we1 = pull_tensor1d_U0_norm_output_38_we1;

assign norm_output_39_address0 = 6'd0;

assign norm_output_39_address1 = pull_tensor1d_U0_norm_output_39_address1;

assign norm_output_39_ce0 = 1'b0;

assign norm_output_39_ce1 = pull_tensor1d_U0_norm_output_39_ce1;

assign norm_output_39_d0 = 32'd0;

assign norm_output_39_d1 = pull_tensor1d_U0_norm_output_39_d1;

assign norm_output_39_we0 = 1'b0;

assign norm_output_39_we1 = pull_tensor1d_U0_norm_output_39_we1;

assign norm_output_40_address0 = 6'd0;

assign norm_output_40_address1 = pull_tensor1d_U0_norm_output_40_address1;

assign norm_output_40_ce0 = 1'b0;

assign norm_output_40_ce1 = pull_tensor1d_U0_norm_output_40_ce1;

assign norm_output_40_d0 = 32'd0;

assign norm_output_40_d1 = pull_tensor1d_U0_norm_output_40_d1;

assign norm_output_40_we0 = 1'b0;

assign norm_output_40_we1 = pull_tensor1d_U0_norm_output_40_we1;

assign norm_output_41_address0 = 6'd0;

assign norm_output_41_address1 = pull_tensor1d_U0_norm_output_41_address1;

assign norm_output_41_ce0 = 1'b0;

assign norm_output_41_ce1 = pull_tensor1d_U0_norm_output_41_ce1;

assign norm_output_41_d0 = 32'd0;

assign norm_output_41_d1 = pull_tensor1d_U0_norm_output_41_d1;

assign norm_output_41_we0 = 1'b0;

assign norm_output_41_we1 = pull_tensor1d_U0_norm_output_41_we1;

assign norm_output_42_address0 = 6'd0;

assign norm_output_42_address1 = pull_tensor1d_U0_norm_output_42_address1;

assign norm_output_42_ce0 = 1'b0;

assign norm_output_42_ce1 = pull_tensor1d_U0_norm_output_42_ce1;

assign norm_output_42_d0 = 32'd0;

assign norm_output_42_d1 = pull_tensor1d_U0_norm_output_42_d1;

assign norm_output_42_we0 = 1'b0;

assign norm_output_42_we1 = pull_tensor1d_U0_norm_output_42_we1;

assign norm_output_43_address0 = 6'd0;

assign norm_output_43_address1 = pull_tensor1d_U0_norm_output_43_address1;

assign norm_output_43_ce0 = 1'b0;

assign norm_output_43_ce1 = pull_tensor1d_U0_norm_output_43_ce1;

assign norm_output_43_d0 = 32'd0;

assign norm_output_43_d1 = pull_tensor1d_U0_norm_output_43_d1;

assign norm_output_43_we0 = 1'b0;

assign norm_output_43_we1 = pull_tensor1d_U0_norm_output_43_we1;

assign norm_output_address0 = 6'd0;

assign norm_output_address1 = pull_tensor1d_U0_norm_output_address1;

assign norm_output_ce0 = 1'b0;

assign norm_output_ce1 = pull_tensor1d_U0_norm_output_ce1;

assign norm_output_d0 = 32'd0;

assign norm_output_d1 = pull_tensor1d_U0_norm_output_d1;

assign norm_output_we0 = 1'b0;

assign norm_output_we1 = pull_tensor1d_U0_norm_output_we1;

assign p_ZZ11llama_layerE11norm_output_10_address0 = 6'd0;

assign p_ZZ11llama_layerE11norm_output_10_address1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_10_address1;

assign p_ZZ11llama_layerE11norm_output_10_ce0 = 1'b0;

assign p_ZZ11llama_layerE11norm_output_10_ce1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_10_ce1;

assign p_ZZ11llama_layerE11norm_output_10_d0 = 32'd0;

assign p_ZZ11llama_layerE11norm_output_10_d1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_10_d1;

assign p_ZZ11llama_layerE11norm_output_10_we0 = 1'b0;

assign p_ZZ11llama_layerE11norm_output_10_we1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_10_we1;

assign p_ZZ11llama_layerE11norm_output_11_address0 = 6'd0;

assign p_ZZ11llama_layerE11norm_output_11_address1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_11_address1;

assign p_ZZ11llama_layerE11norm_output_11_ce0 = 1'b0;

assign p_ZZ11llama_layerE11norm_output_11_ce1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_11_ce1;

assign p_ZZ11llama_layerE11norm_output_11_d0 = 32'd0;

assign p_ZZ11llama_layerE11norm_output_11_d1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_11_d1;

assign p_ZZ11llama_layerE11norm_output_11_we0 = 1'b0;

assign p_ZZ11llama_layerE11norm_output_11_we1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_11_we1;

assign p_ZZ11llama_layerE11norm_output_12_address0 = 6'd0;

assign p_ZZ11llama_layerE11norm_output_12_address1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_12_address1;

assign p_ZZ11llama_layerE11norm_output_12_ce0 = 1'b0;

assign p_ZZ11llama_layerE11norm_output_12_ce1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_12_ce1;

assign p_ZZ11llama_layerE11norm_output_12_d0 = 32'd0;

assign p_ZZ11llama_layerE11norm_output_12_d1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_12_d1;

assign p_ZZ11llama_layerE11norm_output_12_we0 = 1'b0;

assign p_ZZ11llama_layerE11norm_output_12_we1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_12_we1;

assign p_ZZ11llama_layerE11norm_output_13_address0 = 6'd0;

assign p_ZZ11llama_layerE11norm_output_13_address1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_13_address1;

assign p_ZZ11llama_layerE11norm_output_13_ce0 = 1'b0;

assign p_ZZ11llama_layerE11norm_output_13_ce1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_13_ce1;

assign p_ZZ11llama_layerE11norm_output_13_d0 = 32'd0;

assign p_ZZ11llama_layerE11norm_output_13_d1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_13_d1;

assign p_ZZ11llama_layerE11norm_output_13_we0 = 1'b0;

assign p_ZZ11llama_layerE11norm_output_13_we1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_13_we1;

assign p_ZZ11llama_layerE11norm_output_14_address0 = 6'd0;

assign p_ZZ11llama_layerE11norm_output_14_address1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_14_address1;

assign p_ZZ11llama_layerE11norm_output_14_ce0 = 1'b0;

assign p_ZZ11llama_layerE11norm_output_14_ce1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_14_ce1;

assign p_ZZ11llama_layerE11norm_output_14_d0 = 32'd0;

assign p_ZZ11llama_layerE11norm_output_14_d1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_14_d1;

assign p_ZZ11llama_layerE11norm_output_14_we0 = 1'b0;

assign p_ZZ11llama_layerE11norm_output_14_we1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_14_we1;

assign p_ZZ11llama_layerE11norm_output_15_address0 = 6'd0;

assign p_ZZ11llama_layerE11norm_output_15_address1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_15_address1;

assign p_ZZ11llama_layerE11norm_output_15_ce0 = 1'b0;

assign p_ZZ11llama_layerE11norm_output_15_ce1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_15_ce1;

assign p_ZZ11llama_layerE11norm_output_15_d0 = 32'd0;

assign p_ZZ11llama_layerE11norm_output_15_d1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_15_d1;

assign p_ZZ11llama_layerE11norm_output_15_we0 = 1'b0;

assign p_ZZ11llama_layerE11norm_output_15_we1 = pull_tensor1d_U0_p_ZZ11llama_layerE11norm_output_15_we1;

assign pull_tensor1d_U0_ap_continue = ap_continue;

assign pull_tensor1d_U0_ap_start = start_for_pull_tensor1d_U0_empty_n;

assign start_for_pull_tensor1d_U0_din = 1'b1;

endmodule //llama_layer_FFN_1
