// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module kernel_mhsa_RoPE_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        out_0_address0,
        out_0_ce0,
        out_0_we0,
        out_0_d0,
        out_1_address0,
        out_1_ce0,
        out_1_we0,
        out_1_d0,
        out_2_address0,
        out_2_ce0,
        out_2_we0,
        out_2_d0,
        out_3_address0,
        out_3_ce0,
        out_3_we0,
        out_3_d0,
        out_4_address0,
        out_4_ce0,
        out_4_we0,
        out_4_d0,
        out_5_address0,
        out_5_ce0,
        out_5_we0,
        out_5_d0,
        out_6_address0,
        out_6_ce0,
        out_6_we0,
        out_6_d0,
        out_7_address0,
        out_7_ce0,
        out_7_we0,
        out_7_d0,
        in_0_address0,
        in_0_ce0,
        in_0_q0,
        in_1_address0,
        in_1_ce0,
        in_1_q0,
        in_2_address0,
        in_2_ce0,
        in_2_q0,
        in_3_address0,
        in_3_ce0,
        in_3_q0,
        in_4_address0,
        in_4_ce0,
        in_4_q0,
        in_5_address0,
        in_5_ce0,
        in_5_q0,
        in_6_address0,
        in_6_ce0,
        in_6_q0,
        in_7_address0,
        in_7_ce0,
        in_7_q0,
        in_8_address0,
        in_8_ce0,
        in_8_q0,
        in_9_address0,
        in_9_ce0,
        in_9_q0,
        in_10_address0,
        in_10_ce0,
        in_10_q0,
        in_11_address0,
        in_11_ce0,
        in_11_q0,
        in_12_address0,
        in_12_ce0,
        in_12_q0,
        in_13_address0,
        in_13_ce0,
        in_13_q0,
        in_14_address0,
        in_14_ce0,
        in_14_q0,
        in_15_address0,
        in_15_ce0,
        in_15_q0,
        pos_r_dout,
        pos_r_empty_n,
        pos_r_read,
        pos_r_num_data_valid,
        pos_r_fifo_cap
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [6:0] out_0_address0;
output   out_0_ce0;
output   out_0_we0;
output  [31:0] out_0_d0;
output  [6:0] out_1_address0;
output   out_1_ce0;
output   out_1_we0;
output  [31:0] out_1_d0;
output  [6:0] out_2_address0;
output   out_2_ce0;
output   out_2_we0;
output  [31:0] out_2_d0;
output  [6:0] out_3_address0;
output   out_3_ce0;
output   out_3_we0;
output  [31:0] out_3_d0;
output  [6:0] out_4_address0;
output   out_4_ce0;
output   out_4_we0;
output  [31:0] out_4_d0;
output  [6:0] out_5_address0;
output   out_5_ce0;
output   out_5_we0;
output  [31:0] out_5_d0;
output  [6:0] out_6_address0;
output   out_6_ce0;
output   out_6_we0;
output  [31:0] out_6_d0;
output  [6:0] out_7_address0;
output   out_7_ce0;
output   out_7_we0;
output  [31:0] out_7_d0;
output  [5:0] in_0_address0;
output   in_0_ce0;
input  [31:0] in_0_q0;
output  [5:0] in_1_address0;
output   in_1_ce0;
input  [31:0] in_1_q0;
output  [5:0] in_2_address0;
output   in_2_ce0;
input  [31:0] in_2_q0;
output  [5:0] in_3_address0;
output   in_3_ce0;
input  [31:0] in_3_q0;
output  [5:0] in_4_address0;
output   in_4_ce0;
input  [31:0] in_4_q0;
output  [5:0] in_5_address0;
output   in_5_ce0;
input  [31:0] in_5_q0;
output  [5:0] in_6_address0;
output   in_6_ce0;
input  [31:0] in_6_q0;
output  [5:0] in_7_address0;
output   in_7_ce0;
input  [31:0] in_7_q0;
output  [5:0] in_8_address0;
output   in_8_ce0;
input  [31:0] in_8_q0;
output  [5:0] in_9_address0;
output   in_9_ce0;
input  [31:0] in_9_q0;
output  [5:0] in_10_address0;
output   in_10_ce0;
input  [31:0] in_10_q0;
output  [5:0] in_11_address0;
output   in_11_ce0;
input  [31:0] in_11_q0;
output  [5:0] in_12_address0;
output   in_12_ce0;
input  [31:0] in_12_q0;
output  [5:0] in_13_address0;
output   in_13_ce0;
input  [31:0] in_13_q0;
output  [5:0] in_14_address0;
output   in_14_ce0;
input  [31:0] in_14_q0;
output  [5:0] in_15_address0;
output   in_15_ce0;
input  [31:0] in_15_q0;
input  [31:0] pos_r_dout;
input   pos_r_empty_n;
output   pos_r_read;
input  [2:0] pos_r_num_data_valid;
input  [2:0] pos_r_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    pos_r_blk_n;
reg   [31:0] pos_1_reg_183;
reg    ap_block_state1;
wire   [31:0] grp_fu_175_p1;
reg   [31:0] conv_reg_189;
wire    ap_CS_fsm_state4;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_ap_start;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_ap_done;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_ap_idle;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_ap_ready;
wire   [6:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_7_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_7_ce0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_7_we0;
wire   [31:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_7_d0;
wire   [6:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_6_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_6_ce0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_6_we0;
wire   [31:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_6_d0;
wire   [6:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_5_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_5_ce0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_5_we0;
wire   [31:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_5_d0;
wire   [6:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_4_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_4_ce0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_4_we0;
wire   [31:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_4_d0;
wire   [6:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_3_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_3_ce0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_3_we0;
wire   [31:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_3_d0;
wire   [6:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_2_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_2_ce0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_2_we0;
wire   [31:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_2_d0;
wire   [6:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_1_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_1_ce0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_1_we0;
wire   [31:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_1_d0;
wire   [6:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_0_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_0_ce0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_0_we0;
wire   [31:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_0_d0;
wire   [5:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_0_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_0_ce0;
wire   [5:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_2_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_2_ce0;
wire   [5:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_4_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_4_ce0;
wire   [5:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_6_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_6_ce0;
wire   [5:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_8_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_8_ce0;
wire   [5:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_10_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_10_ce0;
wire   [5:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_12_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_12_ce0;
wire   [5:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_14_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_14_ce0;
wire   [5:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_1_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_1_ce0;
wire   [5:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_3_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_3_ce0;
wire   [5:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_5_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_5_ce0;
wire   [5:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_7_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_7_ce0;
wire   [5:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_9_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_9_ce0;
wire   [5:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_11_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_11_ce0;
wire   [5:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_13_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_13_ce0;
wire   [5:0] grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_15_address0;
wire    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_15_ce0;
reg    grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    pos_r_read_local;
wire    ap_CS_fsm_state2;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_ap_start_reg = 1'b0;
end

kernel_mhsa_RoPE_1_Pipeline_VITIS_LOOP_16_1 grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_ap_start),
    .ap_done(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_ap_done),
    .ap_idle(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_ap_idle),
    .ap_ready(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_ap_ready),
    .out_7_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_7_address0),
    .out_7_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_7_ce0),
    .out_7_we0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_7_we0),
    .out_7_d0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_7_d0),
    .out_6_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_6_address0),
    .out_6_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_6_ce0),
    .out_6_we0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_6_we0),
    .out_6_d0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_6_d0),
    .out_5_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_5_address0),
    .out_5_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_5_ce0),
    .out_5_we0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_5_we0),
    .out_5_d0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_5_d0),
    .out_4_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_4_address0),
    .out_4_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_4_ce0),
    .out_4_we0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_4_we0),
    .out_4_d0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_4_d0),
    .out_3_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_3_address0),
    .out_3_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_3_ce0),
    .out_3_we0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_3_we0),
    .out_3_d0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_3_d0),
    .out_2_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_2_address0),
    .out_2_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_2_ce0),
    .out_2_we0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_2_we0),
    .out_2_d0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_2_d0),
    .out_1_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_1_address0),
    .out_1_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_1_ce0),
    .out_1_we0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_1_we0),
    .out_1_d0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_1_d0),
    .out_0_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_0_address0),
    .out_0_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_0_ce0),
    .out_0_we0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_0_we0),
    .out_0_d0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_0_d0),
    .conv(conv_reg_189),
    .in_0_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_0_address0),
    .in_0_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_0_ce0),
    .in_0_q0(in_0_q0),
    .in_2_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_2_address0),
    .in_2_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_2_ce0),
    .in_2_q0(in_2_q0),
    .in_4_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_4_address0),
    .in_4_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_4_ce0),
    .in_4_q0(in_4_q0),
    .in_6_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_6_address0),
    .in_6_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_6_ce0),
    .in_6_q0(in_6_q0),
    .in_8_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_8_address0),
    .in_8_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_8_ce0),
    .in_8_q0(in_8_q0),
    .in_10_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_10_address0),
    .in_10_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_10_ce0),
    .in_10_q0(in_10_q0),
    .in_12_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_12_address0),
    .in_12_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_12_ce0),
    .in_12_q0(in_12_q0),
    .in_14_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_14_address0),
    .in_14_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_14_ce0),
    .in_14_q0(in_14_q0),
    .in_1_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_1_address0),
    .in_1_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_1_ce0),
    .in_1_q0(in_1_q0),
    .in_3_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_3_address0),
    .in_3_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_3_ce0),
    .in_3_q0(in_3_q0),
    .in_5_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_5_address0),
    .in_5_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_5_ce0),
    .in_5_q0(in_5_q0),
    .in_7_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_7_address0),
    .in_7_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_7_ce0),
    .in_7_q0(in_7_q0),
    .in_9_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_9_address0),
    .in_9_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_9_ce0),
    .in_9_q0(in_9_q0),
    .in_11_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_11_address0),
    .in_11_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_11_ce0),
    .in_11_q0(in_11_q0),
    .in_13_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_13_address0),
    .in_13_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_13_ce0),
    .in_13_q0(in_13_q0),
    .in_15_address0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_15_address0),
    .in_15_ce0(grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_15_ce0),
    .in_15_q0(in_15_q0)
);

kernel_mhsa_sitofp_32ns_32_3_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32ns_32_3_no_dsp_1_U489(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(pos_1_reg_183),
    .ce(1'b1),
    .dout(grp_fu_175_p1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_ap_start_reg <= 1'b1;
        end else if ((grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_ap_ready == 1'b1)) begin
            grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        conv_reg_189 <= grp_fu_175_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        pos_1_reg_183 <= pos_r_dout;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        pos_r_blk_n = pos_r_empty_n;
    end else begin
        pos_r_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        pos_r_read_local = 1'b1;
    end else begin
        pos_r_read_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state1 = ((pos_r_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_ap_start = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_ap_start_reg;

assign in_0_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_0_address0;

assign in_0_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_0_ce0;

assign in_10_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_10_address0;

assign in_10_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_10_ce0;

assign in_11_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_11_address0;

assign in_11_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_11_ce0;

assign in_12_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_12_address0;

assign in_12_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_12_ce0;

assign in_13_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_13_address0;

assign in_13_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_13_ce0;

assign in_14_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_14_address0;

assign in_14_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_14_ce0;

assign in_15_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_15_address0;

assign in_15_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_15_ce0;

assign in_1_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_1_address0;

assign in_1_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_1_ce0;

assign in_2_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_2_address0;

assign in_2_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_2_ce0;

assign in_3_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_3_address0;

assign in_3_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_3_ce0;

assign in_4_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_4_address0;

assign in_4_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_4_ce0;

assign in_5_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_5_address0;

assign in_5_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_5_ce0;

assign in_6_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_6_address0;

assign in_6_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_6_ce0;

assign in_7_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_7_address0;

assign in_7_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_7_ce0;

assign in_8_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_8_address0;

assign in_8_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_8_ce0;

assign in_9_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_9_address0;

assign in_9_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_in_9_ce0;

assign out_0_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_0_address0;

assign out_0_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_0_ce0;

assign out_0_d0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_0_d0;

assign out_0_we0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_0_we0;

assign out_1_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_1_address0;

assign out_1_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_1_ce0;

assign out_1_d0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_1_d0;

assign out_1_we0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_1_we0;

assign out_2_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_2_address0;

assign out_2_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_2_ce0;

assign out_2_d0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_2_d0;

assign out_2_we0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_2_we0;

assign out_3_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_3_address0;

assign out_3_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_3_ce0;

assign out_3_d0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_3_d0;

assign out_3_we0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_3_we0;

assign out_4_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_4_address0;

assign out_4_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_4_ce0;

assign out_4_d0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_4_d0;

assign out_4_we0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_4_we0;

assign out_5_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_5_address0;

assign out_5_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_5_ce0;

assign out_5_d0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_5_d0;

assign out_5_we0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_5_we0;

assign out_6_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_6_address0;

assign out_6_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_6_ce0;

assign out_6_d0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_6_d0;

assign out_6_we0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_6_we0;

assign out_7_address0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_7_address0;

assign out_7_ce0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_7_ce0;

assign out_7_d0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_7_d0;

assign out_7_we0 = grp_RoPE_1_Pipeline_VITIS_LOOP_16_1_fu_104_out_7_we0;

assign pos_r_read = pos_r_read_local;

endmodule //kernel_mhsa_RoPE_1
